version: 2.1

orbs:
    node: circleci/node@5.0.2

refs:
    container: &container
        docker:
            - image: node:16
        working_directory: ~/repo
    steps:
        - &PNPM
          run:
              name: Install PNPM
              command: curl -fsSL https://get.pnpm.io/install.sh | sh -
        - &Versions
          run:
              name: Versions
              command: node -v && npm -v && pnpm -v
        - &Install
          run:
              name: Install Dependencies
              command: pnpm install
        - &Build
          run:
              name: Build
              command: pnpm build
        - &Test
          run:
              name: Test
              command: pnpm ci:test

jobs:
    test:
        <<: *container
        steps:
            - checkout
            - *PNPM
            - *Versions
            - *Install
            - *Test
            - *Build

    publish:
        <<: *container
        steps:
            - checkout
            - *Versions
            - *Install
            - *Test
            - *Build
            - run:
                  name: NPM Auth
                  command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            - run:
                  name: Release
                  command: |
                      npx semantic-release && \
                      npx cross-ci :run \
                          npx commit-status success Version "'\${PROJECT_VERSION}'"
workflows:
    version: 2
    all:
        jobs:
            - test:
                  filters:
                      branches:
                          ignore:
                              - master
                              - gh-pages
